
## Gopkg.toml example (these lines may be deleted)

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Dependencies define constraints on dependent projects. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[dependencies]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"

## Overrides have the same structure as [[dependencies]], but supercede all
## [[dependencies]] declarations from all projects. Only the current project's
## [[overrides]] are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[overrides]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overriden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"



[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = "^0.11.5"

[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.8.30"

[[dependencies]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[dependencies]]
  name = "github.com/ucirello/supervisor"
  version = "^0.5.3"

[[dependencies]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[dependencies]]
  name = "github.com/dghubble/oauth1"
  version = "^0.4.0"

[[dependencies]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[dependencies]]
  name = "github.com/docker/docker"
  version = "^17.5.0-ce-rc3"

[[dependencies]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[dependencies]]
  name = "github.com/garyburd/redigo"
  version = "^1.1.0"

[[dependencies]]
  name = "github.com/giantswarm/semver-bump"
  version = "^1.1.1"

[[dependencies]]
  name = "github.com/gin-gonic/gin"
  version = "^1.1.4"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[dependencies]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[dependencies]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/groupcache"

[[dependencies]]
  branch = "master"
  name = "github.com/google/btree"

[[dependencies]]
  branch = "master"
  name = "github.com/iron-io/functions_go"

[[dependencies]]
  branch = "master"
  name = "github.com/iron-io/iron_go3"

[[dependencies]]
  branch = "master"
  name = "github.com/iron-io/runner"

[[dependencies]]
  branch = "master"
  name = "github.com/jmoiron/jsonq"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  name = "github.com/satori/go.uuid"
  version = "^1.1.0"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"

[[dependencies]]
  name = "github.com/urfave/cli"
  version = "^1.19.1"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/sys"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
