kind: ConfigMap
apiVersion: v1
metadata:
  name: functions-config
data:
  MQ_URL: redis://redis-master.default
  DB_URL: postgres://postgres:mysecretpassword@postgresql-master.default/?sslmode=disable
