apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
  labels:
    app: postgresql
    role: datastore
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
    role: datastore